MobiCutz/config/routes.rb
Rails.application.routes.draw do
  resources :stylists
  resources :services
  root 'services#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MobiCutz/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MobiCutz/app/models/service.rb
class Service < ApplicationRecord
    has_many :service_stylists
    has_many :stylists, :through: :service_stylists
end

MobiCutz/app/models/service_stylist.rb
class ServiceStylist < ApplicationRecord
    belong_to :service
    belong_to :stylist
end

MobiCutz/app/models/stylist.rb
class Stylist < ApplicationRecord
    has_many :service_stylists
    has_many :services, :through: :service_stylists
end

MobiCutz/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

MobiCutz/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :person_type)
    end
end

MobiCutz/app/controllers/stylists_controller.rb
class StylistsController < ApplicationController
  before_action :set_stylist, only: [:show, :edit, :update, :destroy]

  # GET /stylists
  # GET /stylists.json
  def index
    @stylists = Stylist.all
  end

  # GET /stylists/1
  # GET /stylists/1.json
  def show
  end

  # GET /stylists/new
  def new
    @stylist = Stylist.new
  end

  # GET /stylists/1/edit
  def edit
  end

  # POST /stylists
  # POST /stylists.json
  def create
    @stylist = Stylist.new(stylist_params)

    respond_to do |format|
      if @stylist.save
        format.html { redirect_to @stylist, notice: 'Stylist was successfully created.' }
        format.json { render :show, status: :created, location: @stylist }
      else
        format.html { render :new }
        format.json { render json: @stylist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stylists/1
  # PATCH/PUT /stylists/1.json
  def update
    respond_to do |format|
      if @stylist.update(stylist_params)
        format.html { redirect_to @stylist, notice: 'Stylist was successfully updated.' }
        format.json { render :show, status: :ok, location: @stylist }
      else
        format.html { render :edit }
        format.json { render json: @stylist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stylists/1
  # DELETE /stylists/1.json
  def destroy
    @stylist.destroy
    respond_to do |format|
      format.html { redirect_to stylists_url, notice: 'Stylist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stylist
      @stylist = Stylist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stylist_params
      params.require(:stylist).permit(:first_name, :last_name, :bio)
    end
end

MobiCutz/app/helpers/application_helper.rb
module ApplicationHelper
end

MobiCutz/app/helpers/services_helper.rb
module ServicesHelper
end

MobiCutz/app/helpers/stylists_helper.rb
module StylistsHelper
end

MobiCutz/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MobiCutz</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

MobiCutz/app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :service_name %>
  </div>


<%= form.radio_button :person_type, 'Child' %> Child<br />
<%= form.radio_button :person_type, 'Women' %>Women<br />
<%= form.radio_button :person_type, 'Men' %> Men<br />


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

MobiCutz/app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

MobiCutz/app/views/services/index.html.erb
<p id="notice"><%= notice %></p>
<p>Hello Everyone </p>

<h1>Services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.person_type %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

MobiCutz/app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

MobiCutz/app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Person Type:</strong>
  <%= @service.person_type %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>

MobiCutz/app/views/stylists/_form.html.erb
<%= form_with(model: stylist, local: true) do |form| %>
  <% if stylist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stylist.errors.count, "error") %> prohibited this stylist from being saved:</h2>

      <ul>
      <% stylist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :stylist_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :stylist_last_name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_field :bio, id: :stylist_bio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

MobiCutz/app/views/stylists/edit.html.erb
<h1>Editing Stylist</h1>

<%= render 'form', stylist: @stylist %>

<%= link_to 'Show', @stylist %> |
<%= link_to 'Back', stylists_path %>

MobiCutz/app/views/stylists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stylists</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stylists.each do |stylist| %>
      <tr>
        <td><%= stylist.first_name %></td>
        <td><%= stylist.last_name %></td>
        <td><%= stylist.bio %></td>
        <td><%= link_to 'Show', stylist %></td>
        <td><%= link_to 'Edit', edit_stylist_path(stylist) %></td>
        <td><%= link_to 'Destroy', stylist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stylist', new_stylist_path %>

MobiCutz/app/views/stylists/new.html.erb
<h1>New Stylist</h1>

<%= render 'form', stylist: @stylist %>

<%= link_to 'Back', stylists_path %>

MobiCutz/app/views/stylists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @stylist.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @stylist.last_name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @stylist.bio %>
</p>

<%= link_to 'Edit', edit_stylist_path(@stylist) %> |
<%= link_to 'Back', stylists_path %>